moveit_server:
  ros__parameters:
    collision_object_frame: "world"
    base_frame_id: "link_base"
    end_effector_frame_id: "link_eef"
    orientation_tolerance:
      x: 0.75
      y: 0.75
      z: 0.75
    trajectory:
      velocity_scaling_factor: 0.2
      acceleration_scaling_factor: 0.4
      planning_attempts: 5
      planning_time: 2.0
      goal_tolerance: 0.005
      goal_orientation_tolerance: 0.005
    sync:
      velocity_scaling_factor: 0.8
      acceleration_scaling_factor: 1.0
      planning_attempts: 5
      planning_time: 2.0
      goal_tolerance: 0.005
      goal_orientation_tolerance: 0.005
    workspace:
      minx: -1.0
      miny: -1.0
      minz: -1.0
      maxx: 1.0
      maxy: 1.0
      maxz: 1.0
